doofinder/doofinder-woocommerce

- doofinder-for-woocommerce/lib/src/Management/ManagementClient.php
Fix: https://github.com/doofinder/helpapp/issues/13358
This issue was fixed by Antonio in our php library: https://github.com/doofinder/php-doofinder/pull/60
> Fix parameters

- doofinder-for-woocommerce/assets/js/wizard.js
- doofinder-for-woocommerce/includes/class-setup-wizard.php
> fix: setup wizard step 1

- doofinder-for-woocommerce/includes/class-post.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/includes/settings/settings-data.php
Added a checkbox to activate/deactivate update on save in Woocommerce.
> Added update on save setting

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-settings-page.php
- doofinder-for-woocommerce/readme.txt
- package.json
Sorry for the formatting changes, the important change is at **doofinder-for-woocommerce/includes/class-settings-page.php** line 323
> SP-495 | Fix delete attributes button

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/readme.txt
- package.json
> Added Update Manager

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/readme.txt
Now the final step should reset the wizard step to 1.
> Fixed final step bug

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-doofinder-api.php
- doofinder-for-woocommerce/readme.txt
- package.json
This PR adds some improvements to the previous PR #136
> Fix Multilanguage Indexation Issues

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-doofinder-api.php
- doofinder-for-woocommerce/readme.txt
- package.json
Revert the create_temporary_index refactor as it is causing some errors
> Revert create_temporary_index refactor 

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-doofinder-api.php
- doofinder-for-woocommerce/includes/class-data-index.php
- doofinder-for-woocommerce/readme.txt
- package.json
There was a bug while indexing in multilanguage that made skip the index replace with the temporary one (including the updates).
I've added a condition to avoid this problem.
I've also included all reverted changes made in the previous #137 "Fix Multilanguage Indexing Issues" PR
> Fix Multilanguage Indexing Issues

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-doofinder-api.php
- doofinder-for-woocommerce/includes/class-index-interface.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/readme.txt
- package.json
Fixed some bugs with new language codes
> Fixed language code issues

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/readme.txt
- package.json
> Update version to test release workflow

- doofinder-for-woocommerce/includes/class-data-feed.php
- doofinder-for-woocommerce/includes/data-feed/class-data-feed-item.php
- doofinder-for-woocommerce/includes/settings/class-attributes.php
In this PR, I've moved the attributes from the parent to each variant.
Also, I've added a new function to remove the product attributes that do not have stock of any variant.
Note: Sorry for all the formatting changes, I've added some comments to facilitate the review.
> Add variant attributes

- Dockerfile
- docker-compose.yml
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/settings/settings-layer.php
- doofinder-for-woocommerce/readme.txt
- package.json
required by [#160](https://github.com/doofinder/doofinder-woocommerce/issues/160)
> Unplugged-160 | Remove internal search option

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/settings/class-attributes.php
- doofinder-for-woocommerce/readme.txt
- package.json
Required by [support #825](https://github.com/doofinder/support/issues/825)
> Unplugged 825 | Fix custom attributes indexation

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-admin-notices.php
- doofinder-for-woocommerce/includes/class-migration.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/readme.txt
I've fixed an issue with settings migration that were causing the migration to never end.
I've also fixed a bug in the path of the green checkmark image.
> Fix migrations and image path

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
This PR fixes a bug in the previous update (2.0.2)
> Fix update bug

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
> Fixed update bug

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-rest-api-handler.php
- doofinder-for-woocommerce/includes/class-thumbnail.php
- doofinder-for-woocommerce/readme.txt
- package.json
Requested-by: [doofeeds/issues/544](https://github.com/doofinder/doofeeds/issues/544)
- Modified products and variants rest response to include a new "image_link" field
This will also require a doofeeds update to access this new field.
> Fix product image size

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-rest-api-handler.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Requested-by: [doofeeds/issues/544](https://github.com/doofinder/doofeeds/issues/544)
- Added the parent image if the variant image is empty.
> Add parent image to variants

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-rest-api-handler.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Requested-by: [support/issues/1279](https://github.com/doofinder/support/issues/1279)
- Fixed product variations regex
- Added an if to check that the request comes from our environment
- Added logs on invalid product
- Check if valid WC_Product in add_df_prices
Notice: This version should be deployed after updating DooFeeds WordPress Client to add the needed HTTP header to identify our requests.
> Fix REST API Handler invalid product issues

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-rest-api-handler.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Requested-by: [support/issues/1262](https://github.com/doofinder/support/issues/1262)
This PR fixes an issue with relative image URLs.
We have added a condition to check if the image URL is relative, and in that case we add the base URL.
> Fix relative image uris

- doofinder-for-woocommerce/assets/css/admin.css
- doofinder-for-woocommerce/assets/js/admin.js
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/includes/class-migration.php
- doofinder-for-woocommerce/includes/class-settings.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/includes/settings/attributes.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/includes/settings/class-register-settings.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Requested-by: [doofinder-woocommerce/issues/180](https://github.com/doofinder/doofinder-woocommerce/issues/180)
- Added the custom attributes settings form.
> Add custom attributes settings

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-update-on-save.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by: 
https://github.com/doofinder/support/issues/1362
> Fix bug that was saving non-indexable post types in the database in doofinder_update_on_save

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-settings.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Requested-by: [https://github.com/doofinder/support/issues/1450](https://github.com/doofinder/support/issues/1450)
- Fixed a bug while registering our custom cron_schedules.
> Fix cron schedules issue

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by https://github.com/doofinder/doofinder-woocommerce/issues/195
Default currency is not correct, we take currency from woocommerce plugin.
> We take currency from woocomerce plugin

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/includes/class-migration.php
- doofinder-for-woocommerce/includes/class-settings.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/includes/class-thumbnail.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by: https://github.com/doofinder/doofinder-woocommerce/issues/170
> Check data migration process when a customer upgrades to the new version

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/includes/class-index-status-handler.php
- doofinder-for-woocommerce/includes/class-log.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/includes/class-update-on-save.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by https://github.com/doofinder/doofinder-woocommerce/issues/131
I have normalized and cleaned the plugin's log structure and built an update function so that the old logs are archived and new ones are started.
> Log cleaning and normalization

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-update-on-save-index.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by https://github.com/doofinder/doofinder-woocommerce/issues/131
We have had problems with the deploy and we created this version variant to perform a clean deploy.
> Fix deploy clenning logs

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-admin-notices.php
- doofinder-for-woocommerce/includes/class-migration.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Requested by: 
- https://github.com/doofinder/support/issues/1715
A bug that occurred while migrating the api_host from prior plugin versions has been solved.
> Fix api host migration issues

- doofinder-for-woocommerce/assets/js/admin.js
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-reset-credentials.php
- doofinder-for-woocommerce/includes/class-update-on-save.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
We have been contacted by https://patchstack.com/ to inform us that the AJAX requests made from the admin of our plugin were not secure because the nonce fields were not being utilized.
Abdi Pranata discovered and reported this Broken Access Control vulnerability in WordPress Doofinder for WooCommerce Plugin to Patchstack.
The plugin ajax request does not implement nonce, which can be executed by lower privileged user
1. Do static analysis in
/doofinder-for-woocommerce/assets/js/admin.js
2. You will see ajax request "doofinder_force_update_on_save" and "doofinder_reset_credentials"
3. Since there are not nonce verified, we can make request like this
```
POST /belanja/wp-admin/admin-ajax.php HTTP/1.1
Host: localhost
Cookie: [PASTE OOOKIE]
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; …
```
> Added Ajax nonces to improve security

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/includes/class-thumbnail.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- Check if image is corrupted
- Set price (from regular_price)
> Check if the original image is corrupted

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by: https://github.com/doofinder/support/issues/1931
> Fix XSS issue

- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
- doofinder-for-woocommerce/includes/settings/class-register-settings.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
Required by:
https://github.com/doofinder/support/issues/1915 and https://github.com/doofinder/doofinder-woocommerce/issues/234
> Fix corrupt img problems and improve XSS secure

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
Required by:  https://github.com/doofinder/support/issues/1963
> Doofinder plugin affects WP admin CSS

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-update-on-save-api.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
> Fix protocol dooplugins endpoint and post error last page

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- Fix para cuando los campos meta han sido renombrados por otro nombre (hay que mirar la clave attribute no la field)
- Fix para que cuando los atributos basic han sido renombrados se elimine la clave original y se deje solo la clave renombrada.
> Fix meta field keys attributes

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-settings.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required-by: https://github.com/doofinder/support/issues/1979
Added `stock_status` to the reserved field names to avoid indexing issues.
> Fix Stock Status reserved field

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Ahora lo que hacemos es no hacer ningún tipo de filtrado con el campo de indexation, de tal manera que le dejamos la responsabilidad de filtrar a doofeeds/items_transformation
> Adding indexation field

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-update-on-save-api.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
I found this improvement by researching this ticket:  https://github.com/doofinder/support/issues/2000
And also fix this error: https://github.com/doofinder/support/issues/2006
> Improve JS and CSS secure load and fix update on save bug

- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/support/issues/2015
Related to:
- https://github.com/doofinder/doofinder-woocommerce/pull/245
> PLUGINRANGERS-2015 | Packages version bump since I forgot it in the previous PR

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/includes/helpers/class-store-helpers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by: https://github.com/doofinder/doofinder-woocommerce/issues/252
> Restore api options

- doofinder-for-woocommerce/assets/css/admin.css
- doofinder-for-woocommerce/assets/css/doofinder-notice.css
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-helpers.php
- doofinder-for-woocommerce/includes/class-migration.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/includes/settings/class-register-settings.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Requested-by: 
- https://github.com/doofinder/doofinder-woocommerce/issues/251
- https://github.com/doofinder/support/issues/2091
> Refactor plugin host urls

- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
Required by: https://github.com/doofinder/support/issues/2133
> Exclude variants attributes information from parent

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-log.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/support/issues/2148
> PLUGINRANGERS-2148 | Changed log path to wp-content/uploads folder

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/support/issues/2167
> PLUGINRANGERS-2167 | Fixed HTML entities encoding in posts/pages title

- doofinder-for-woocommerce/assets/js/df-add-to-cart.js
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/dfcommon/issues/1101
Until now, we were waiting until the timeout of the Live Layer Deferred Promise and we were assuming that everything was always ok even in case of error. This PR improves this process
> PLUGINRANGERS-1101 | Manage add to cart DeferredPromise

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Solves https://github.com/doofinder/support/issues/2179
It looks like when the image for the page is in png, it is not returned in the response from the API where we expect it.
We are making a change so if this happens, we will get the image independtly using methods from our Thumbnail class.
> Support 2179 issue

- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
related by: https://github.com/doofinder/support/issues/2179
The version updated in: https://github.com/doofinder/doofinder-woocommerce/pull/276
> [Woocommerce] - Fix custom types image links

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-js-layer.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by: https://github.com/doofinder/support/issues/2251
Add in readme improve for https://github.com/doofinder/doofinder-woocommerce/pull/277
> [Woocommerce] - Fix script injection in multilang

- doofinder-for-woocommerce/includes/api/class-update-on-save-api.php
Related by: https://github.com/doofinder/support/issues/2271
> [Woocommerce] - Improve Update on Save API handle response

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
We were saving the wrong language code, so indexing in some languages did not work correctly. And search engines were not created for all languages, as the codes were being stepped on.
> [Woocommerce] - Fix multi-lang installation params for indexation

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-landing.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- https://github.com/doofinder/support/issues/2287
- Updated the `Landing::init()` function to optimize site performance by reducing the frequency of rewrite rule flushes. Previously, rewrite rules were flushed on every page request, leading to decreased site speed. Now, we perform a check for changes before flushing rewrite rules, ensuring they are only flushed when necessary.
> Fix landings performance issues

- doofinder-for-woocommerce/assets/js/admin.js
Required by: https://github.com/doofinder/support/issues/2404
> [Custom Attributes] - Add underscore or point check

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Este cambio para corregir un error que le da a un cliente al hacer la indexación con PHP 8
Los detalles del error están en este ticket: https://github.com/doofinder/support/issues/2416
> Add validation to avoid fatal error on PHP 8 if index is not defined

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/dfcommon/issues/1190
> PLUGINRANGERS-1190 | Added a video in readme.txt

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by #293.
Index parent product with the URL of the variant with the minimum price
> feat: Index parent product with URL of min variant

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/support/issues/2508
Before (color as array):
After (color as string):
> PLUGINRANGERS-2508 | Changed attributes return type from array to string if there is only 1 value

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/support/issues/2522
However this is another bug, not directly related with the previous one
> PLUGINRANGERS-2522 | Fatal error: [] operator not supported for strings

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/readme.txt
Required by https://github.com/doofinder/support/issues/2556
> Dont use friendly urls for callback

- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/support/issues/2556
> PLUGINRANGERS-2556 | Version bump

- doofinder-for-woocommerce/includes/api/class-landing-api.php
- doofinder-for-woocommerce/includes/api/class-reset-credentials-api.php
- doofinder-for-woocommerce/includes/api/class-store-api.php
- doofinder-for-woocommerce/includes/api/class-update-on-save-api.php
- doofinder-for-woocommerce/includes/class-log.php
- doofinder-for-woocommerce/includes/class-migration.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/includes/class-update-manager.php
- doofinder-for-woocommerce/includes/class-update-on-save-index.php
- doofinder-for-woocommerce/includes/helpers/class-helpers.php
Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/304
>  PLUGINRANGERS-304 | Applied automatic code style changes by WooCommerce lint, part 7

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by: https://github.com/doofinder/support/issues/2611
> WP - 500 error posts when image is not set

- .github/workflows/php.yml
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-post-category.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product-category.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-single-script.php
- doofinder-for-woocommerce/includes/settings/attributes.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/includes/settings/class-helpers.php
- doofinder-for-woocommerce/includes/settings/class-register-settings.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/304
I've provoked an error in the PHP Standards on purpose (commit https://github.com/doofinder/doofinder-woocommerce/pull/318/commits/9937b5264e96036c30323e1d461ea63b212b1272) just to test the GitHub CI:
>  PLUGINRANGERS-304 | Applied automatic code style changes by WooCommerce lint, part 8

- doofinder-for-woocommerce/readme.txt
> Updated readme

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- Fix issues with Settings namespace
> Fix issues with Settings namespace for certain sites.

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-post.php
- doofinder-for-woocommerce/includes/class-settings.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Moved `add_schedules` function to the plugin class
> Fix settings namespace issues v2

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-settings.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- Fixes the top level menu name that was modified by mistake in the previous release.
> Fix top level menu name

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
The problem is that the min-hago-test data is removed because the array_filter function is configured to filter out values that are considered “empty” (including 0, which in PHP evaluates to empty).
Since the value of min-hago-test is 0, the array_filter function removes it.
To avoid this, we can modify the array_filter function so that it only filters out null or empty values, but not those that are 0.
Before:
```
[
{
"average_rating": "0.00",
"catalog_visibility": "visible",
"categories": [
"Sin categorizar"
],
"id": 32,
"price": 20,
"purchasable": true,
"regular_price": 20,
"status": "publish",
"slug": "product-test-2",
"stock_status": "instock",
"df_indexable": "auto",
"image_link": "https://9314c37b-0ef5-499b-b938-d87b1c691106.clouding.host/wp-content/uploads/woocommerce-placeholder-3 …
```
> [Custom Attribute] - Fixed when is empty value

- doofinder-for-woocommerce/includes/helpers/class-template-engine.php
- doofinder-for-woocommerce/views/wizard-step-3.php
- doofinder-for-woocommerce/views/wizard-step.php
- phpcs.xml
Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/304
> PLUGINRANGERS-304 | Applied automatic code style changes by WooCommerce lint, part 9

- doofinder-for-woocommerce/assets/js/df-add-to-cart.js
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-add-to-cart.php
- doofinder-for-woocommerce/includes/class-endpoints.php
- doofinder-for-woocommerce/includes/class-post.php
- doofinder-for-woocommerce/includes/class-reset-credentials.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/includes/class-update-on-save.php
- doofinder-for-woocommerce/includes/settings/class-register-settings.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- phpcs.xml
Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/304
Finally, the last one! :smile:
> PLUGINRANGERS-304 | Applied automatic code style changes by WooCommerce lint, part 10

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-js-layer.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/315
Proof that works:
> PLUGINRANGERS-315 | Declare usage of Helper class (bugfix)

- Makefile
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- https://github.com/doofinder/support/issues/2832
- Normalize attribute slug and attribute name.
> Fix custom attributes dashes issue

- doofinder-for-woocommerce/assets/js/wizard.js
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/readme.txt
- doofinder-for-woocommerce/views/wizard.php
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/support/issues/2870
> PLUGINRANGERS-2870 | [SUPPORT] Fixed nonce verification in Store Wizard step 2

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/includes/settings/class-register-settings.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/dooplugins/issues/881
> PLUGINRANGERS-881 | Changed search bar references to script in texts

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/class-update-on-save-api.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/includes/class-setup-wizard.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:https://github.com/doofinder/doofinder-woocommerce/issues/330
> [BUGFIX] - Update on Save multilang

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/351
> PLUGINRANGERS-351 | Prevented an error by initializing `$image_sizes` array

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by https://github.com/doofinder/support/issues/3141.
> Avoiding setting price to 0 when regular price is 0

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/353
> PLUGINRANGERS-353 | Taken into account scheduled dates in sale prices

- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
Required by:
- https://github.com/doofinder/support/issues/3184
> PLUGINRANGERS-3184 | Quick fix, changed per_page to lang

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/class-settings.php
- doofinder-for-woocommerce/includes/helpers/class-helpers.php
- doofinder-for-woocommerce/includes/settings/class-accessors.php
- doofinder-for-woocommerce/includes/settings/class-renderers.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/dooplugins/issues/1138
> PLUGINRANGERS-1138 | Added support for Asia-Pacific region

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- Added `category_merchandising` field.
> Added category merchandising field

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
- Trim category_merchandising slashes
> Trim category_merchandising

- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
fixes https://github.com/doofinder/support/issues/3693
> Fix categories computation

- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
fixes https://github.com/doofinder/support/issues/3723
> Index type field for products

- doofinder-for-woocommerce/assets/js/doofinder-integration-klaviyo.js
- doofinder-for-woocommerce/doofinder-for-woocommerce.php
- doofinder-for-woocommerce/readme.txt
- package-lock.json
- package.json
Required by:
- https://github.com/doofinder/dooplugins/issues/1402
> PLUGINRANGERS-1402 | Simplified Integrations logic, moved almost all the parts to the single script
