doofinder-for-woocommerce/includes/class-internal-search.php

With this change developers can use WooCommerce filters with Doofinder internal search. New filter `woocommerce_doofinder_internal_search_params` is added.

[Internal Search] Add query params hook filter

---

doofinder-for-woocommerce/assets/js/df-add-to-cart.js
doofinder-for-woocommerce/assets/js/wizard.js
doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-add-to-cart.php
doofinder-for-woocommerce/includes/class-setup-wizard.php
doofinder-for-woocommerce/readme.txt
doofinder-for-woocommerce/views/wizard.php
package.json

The goal of this PR is to avoid some 4xx errors while doing requests to the wp-rest api.
- I've replaced the previous wp-rest endpoint callback to connect with doofinder after login with a postmessage sent from the login window.
- I've also replaced the add_to_cart product info wp-rest endpoint with an admin-ajax call.

Fix wordpress api connection

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-data-feed.php
doofinder-for-woocommerce/readme.txt
package.json

Until now, the error level was modified at the level of the entire web, which caused the client's error_level to be replaced with E_ALL & ~E_NOTICE (All except notices).
This caused errors such as E_DEPRECATED to be enabled throughout the web.
To fix this, I've modified the **maybe_suppress_notices** function so that, based on the client's error_level, it removes the notices.
On the other hand, that function is no longer executed every time the plugin loads, but is called only when generating the feed, which is where it is needed.
Lastly, I've created another function, **maybe_restore_notices**, which resets the previous value with the intention of calling it after the feed is generated.

Removed unwanted error logs that were being displayed

---

doofinder-for-woocommerce/includes/api/class-doofinder-api.php

Fixed an error that occurred when all languages were indexed after a specific one had been indexed.
The problem was due to the fact that, within the send_batch function, it was trying to add elements to a temporary index that for some reason does not exist.
The solution has been to handle the NotFound exception, reset the variable $indexing_data->temp_index and call send_batch() again to force the creation of the temporary index.

Fix Multilanguage Indexation Issues

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/lib/src/Management/ManagementClient.php
doofinder-for-woocommerce/readme.txt
package.json

This PR solves an issue when you try to remove the sale_price of a product.
I've changed the method used to update the product from updateItem to createItem, as createItem uses post instead of patch method in order to remove the fields we want (special_price)

Fix sale_price in update on save

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/class-store-api.php
doofinder-for-woocommerce/includes/class-data-feed.php
doofinder-for-woocommerce/includes/class-data-index.php
doofinder-for-woocommerce/includes/class-index-interface.php
doofinder-for-woocommerce/includes/class-setup-wizard.php
doofinder-for-woocommerce/includes/class-update-manager.php
doofinder-for-woocommerce/includes/helpers/class-helpers.php
doofinder-for-woocommerce/includes/multilanguage/class-wpml.php
doofinder-for-woocommerce/readme.txt
package.json

Now we send the full locale code (en-US) instead of the language code (en) to the create-store endpoint.

Use locale code instead of language

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/data-feed/class-data-feed-item.php
doofinder-for-woocommerce/includes/settings/class-attributes.php
doofinder-for-woocommerce/readme.txt
package.json

A client had some errors with arrow functions, as these were introduced in PHP 7.4, and they are using PHP 7.3
I've replaced arrow functions by anonymous functions

Replaced arrow functions by anonymous functions

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-update-manager.php
doofinder-for-woocommerce/readme.txt
package.json

Requested-by: [support/issues/1179](https://github.com/doofinder/support/issues/1179)
We have discovered an issue with the indexation result response. 
When an error occurs, Doofeeds returns the whole body of a 404 response.
Example:
```
[download][product] something went wrong with feed download, Wordpress: a problem has occurred in the web server. \n\n<!DOCTYPE html>\n\n<html lang=\"pt-PT\" class=\"supports-fontface\">\n\n<head>\n\t<meta charset=\"UTF-8\">\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" />\n\t<meta name=\"apple-itunes-app\" content=\"app-id=1580786296\">\n\t<meta name=\"facebook-domain-verification\" content=\"m4rzd3s3cozqzah2jev9uqvdzjtqwh\" />\n\n\t<link rel=\"pingback\" …
```

Fix indexing failed error message issues

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-tax-prices-handler.php
doofinder-for-woocommerce/readme.txt
package.json

Required by: https://github.com/doofinder/support/issues/1204
The prices are usually displayed in the correct way with the taxes applied as expected. However, the users can apply two inconsistent setting that might lead to errors, so there are 4 possible situations:
-  Yes, I will enter prices inclusive of tax + Display prices in the shop including tax --> consistent case, the price shown on the REST API will match the one shown on the shop:
- No, I will enter prices exclusive of tax +  Display prices in the shop excluding tax --> consistent case, almost the same as the previous case, the prices will match again, but in this case the taxes are excluded from both.
- Yes, I will enter prices inclusive of tax +Display prices in the shop excluding tax --> inconsistent case, the REST API …

UNPLUGGED-1204 | Added a way to show prices with the correct taxes in the REST API

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/settings/class-renderers.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Fix visual bug in product data setting when array is null

---

doofinder-for-woocommerce/readme.txt

Required by https://github.com/doofinder/doofinder-woocommerce/issues/189
We have to change version in the next PR

Change version for Wordpress 6.3

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-rest-api-handler.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Requested-by: https://github.com/doofinder/support/issues/1359
We encountered inconsistencies with prices while indexing from our local environment and the production environment. The problem arises from the WooCommerce REST API, which returns prices based on the geolocation of the requester. In this case, our server is in Ireland, resulting in the application of Irish taxes (23% VAT) rather than the base location taxes (21% VAT), leading to different prices being returned.
Solution: Implement a filter to return prices applying the base location taxes when receiving requests from Doofinder.

Adjust non base location prices

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/class-store-api.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

I have detected several problems with the migration when it is multi-language
One of them is that there are times that the multi-language plugins do not assign a prefix to the default language, so they do not match in those cases. There is an easier way to see that it matches without using the prefix.

Fix of several problems with migration when it is multi-language

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-rest-api-handler.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required-by:
- https://github.com/doofinder/support/issues/1628
One of our clients is having issues with sale prices, so I've added a condition that checks if the price is equal to '0' and returns an empty string instead.
This way the price will be ignored instead of indexing the product with a price of '0'.

Fix zero prices in Rest API response

---

.github/workflows/php.yml
.gitignore
composer.json
composer.lock
doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-settings.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json
phplint.sh

Required by: 
- https://github.com/doofinder/support/issues/1783
Sets minimum WP version as 5.6 (due to the Application Passwords) and minimum PHP version to 7.0. Also adds a simple lint both locally and in Github Actions to check always the compatibility of the code with several version in a automated way.
First working test of local tests (PHP 5.6 has been included in the tests to see the possible failures):

PLUGINRANGERS-1783 | Test PHP lint + required minimum PHP and WP version

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt

Required by:
- https://github.com/doofinder/support/issues/2015
With this PR, special HTML entities like `&amp;` will be properly encoded (e.g. `&amp;` as `&`).

PLUGINRANGERS-2015 | Properly decode HTML entities for attributes

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-landing.php
doofinder-for-woocommerce/readme.txt
doofinder-for-woocommerce/views/wizard-step.php
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/2000
We have detected that our plugin can create some conflicts with the WPML one due to the rewrite rules applied for the landings, since WPML tries to rewrite the base in the .htaccess thus causing the issue. More info in: https://wpml.org/errata/htaccess-is-rewritten-with-language-folder/

PLUGINRANGERS-2000 | Avoided 500 errors with WPML + simplified some ternary operators

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/2014
Some customers has some non-purchasable items (e.g. auction items), but they want to customize the template using the real stock status. This PR keeps the stock_status field in the response.

PLUGINRANGERS-2014 | Prevent stock_status field removal

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

This PR fixes issues https://github.com/doofinder/support/issues/2037 and https://github.com/doofinder/support/issues/2079
The first issue was caused by the code deleting all of the elements in the custom_attributes array if they didn't have the key "name". To fix it we check first if we are setting an empty array as the custom attrbiute, and if so we leave the original, full array. 
The second was caused by the wordpress funcion "get_sale_price" from WC_Product not returning a value. We believe this happens when a product has variants (https://stackoverflow.com/a/51065777). We are making a fix by calculating the sales price ourselves, looking at the regular price and the price.

Fix sale price not indexing and custom_attribute not exporting

---

docker-compose.yml

This was discussed here
https://github.com/doofinder/doofinder-woocommerce/issues/218#issuecomment-2003188290
Adding volume to store the wordpress database

Store mysql db in a volume

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

- https://github.com/doofinder/support/issues/2228
- Added a try/catch block to avoid fatal errors while obtaining image link for custom endpoint items.

Fix custom endpoint issues while obtaining image link

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-update-on-save.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/2305
This PR solves a bug where the WHERE field was being used as id instead of post_id. However it might not be totally related to the bug reported by the customer which claims that his web is down when our plugin is enabled.

PLUGINRANGERS-2305 | Fixed wpdb query on Update on Save

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/class-update-on-save-api.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/2315
`WP_Http` is failing since it requires a `use` statement or being used as `\WP_Http`

PLUGINRANGERS-2315 | Added use statement to properly use WP_Http class

---

doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt

Required by:
- https://github.com/doofinder/support/issues/2314
Error:
`Uncaught Error: Cannot unset string offsets in /var/www/vhosts/morger.ch/httpdocs/cms2013/wp-content/plugins/doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php:183 `

PLUGINRANGERS-2314 | Fatal error unsetting string

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-update-manager.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

We have solved a problem in our plugin database update check. Before, if there were no updates for the current version, the plugin would hang onto the last updated version, triggering unnecessary update checks. Now, even if there's no update function, the app recognizes it's up to date. This means the database always reflects the latest version, and updates are only checked when the version changes.

Fixed plugin version check issue

---

doofinder-for-woocommerce/readme.txt

Required by:
- https://github.com/doofinder/dooplugins/issues/476
Trick: use this tool (https://wpreadme.com/) to visualize the changes in the readme.txt (It's not 100% accurate since it translates & as &amp; unlike WP real plugin repository, but it's something).
It seems that the translations must be applied from a visual interface: https://translate.wordpress.org/projects/wp-plugins/doofinder-for-woocommerce/

PLUGINRANGERS-476 | Changed some parts of the readme.txt

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/class-store-api.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-single-script.php
doofinder-for-woocommerce/readme.txt
doofinder-for-woocommerce/views/single-script.php
package-lock.json
package.json

Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/285
The GIF proves that the request requires a security header to be called and that the old script gets replaced by the new one automatically. However, it must be tested also with WPML enabled.
Multilanguage example:

PLUGINRANGERS-285 | Implemented new endpoint to replace the script with the single one

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/2522
It should fix a bug related to https://github.com/doofinder/doofinder-woocommerce/pull/299 where we were assuming that the inner data will be always an array (it could be null too)
Proof that works:

PLUGINRANGERS-2522 | Added array check before attribute length retrieval

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/2522
Fixes PHP >= 8.0 for: https://github.com/doofinder/doofinder-woocommerce/pull/300
While the last fix was valid for PHP <= 7.4, is not valid for PHP >= 8.0 because is_array is not enough to prevent errors while accesing keys that are not present in the array, so `! empty() `or `array_key_exists()` must be used before.
Proof
PHP 7.4:
Works with a warning
PHP 8.0
Does not work at all:
With ! empty() checking:

PLUGINRANGERS-2522 | Added empty check before is array to prevent errors on PHP >= 8.0

---

doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php

Required by doofinder/support#2642.

Avoid error when the media_details is an empty stdObject

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/includes/class-settings.php
package-lock.json
package.json

- https://github.com/doofinder/support/issues/2588
- Moved cron_schedules add_filter to the main plugin file.
- Fixed some errors that occurred when accessing invalid woocommerce product properties.

Fix cron schedules order issues

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

We have a bug in the update on save functionality when it is launched from the cron (https://github.com/doofinder/doofinder-woocommerce/issues/328).
The cron execution context does not have a user set, so the requests to the wordpress internal API fail. In this PR we modify the `woocommerce_rest_check_permissions` filter so that it allows requests to pass only in this case.
Thanks to @eugeniobonifacio for the suggestion of the fix!

Fix update on save cron bug

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt
package.json

Required by https://github.com/doofinder/support/issues/2800
Con el cambio introducido en este [commit](https://github.com/doofinder/doofinder-woocommerce/commit/5d3dfa94fa8f1e7225a238b722c265070fe70139#diff-2165d17b8be746fcfa129c9a62c441135a710c4a20bf13569166be566e7ee323R581) se cambia empty por is_null, eso ha provocado que sale_price no se eliminara de la respuesta si era empty. Al menos en un cliente a provocado que en la capa los productos sin descuentos si muestren con descuento del 100%, también afectaba otros campos que dependían del valor de sale_price.

Remove sale_price from response if it is empty

---

.github/workflows/create_release.yml
doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/329
Proof that works:
WP Admin:
Doomanager:

PLUGINRAGERS-329 | Custom attributes are used in df_variants_information now

---

doofinder-for-woocommerce/includes/settings/class-register-settings.php

Required by:
- https://github.com/doofinder/doofinder-woocommerce/issues/329
Version bump is not needed since it will be included with another previously merged PR which has already increased the version.

PLUGINRANGERS-339 | Fixed typo in previous description text

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/class-store-api.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/includes/class-setup-wizard.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/3038
Actually fixes:
- https://github.com/doofinder/support/issues/3053
This PR prevents prices to be returned as false, so instead, they will be treated as 0, so '' will be returned instead (tested directly on the customer's WP and works):
Apart from this, I have noticed that the fix applied on https://github.com/doofinder/support/issues/3053 was not working as expected, since now the original SE was being retrieved as "no-hash". Now every SE have their hashids correctly assigned:
```json
{
"store_options":{
"url":"http:\\/\\/david-wordpress.ngrok.doofinder.com",
"api_pass":"************************",
"api_user":"*****",
"df_token":"************************"
},
"platform":"woocommerce",
"search_engines":{ …
```

PLUGINRANGERS-3038 | Prevent false prices + actual bugfix of normalization

---

doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php

Required by:
- https://github.com/doofinder/support/issues/3184
I haven't increased the version since my intention is to merge this PR along with this one: https://github.com/doofinder/doofinder-woocommerce/pull/355

PLUGINRANGERS-3184 | Prevented undefined params warning on custom endpoint

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by: https://github.com/doofinder/support/issues/3269
Basically, the fields were updated with those of the custom attributes, but when a request was made, the fields of the request that were not being updated were used.

Bugfix Update on save dont update custom attributes

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-setup-wizard.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/3442
Basically, if no multilang plugin (WPML) is active, the $language value was `''`, so $language['code'] cannot be retrieved.

PLUGINRANGERS-3442 | Prevented error when creating stores via Store Wizard if no multilang plugin is active

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-custom.php
doofinder-for-woocommerce/includes/api/endpoints/class-endpoint-product.php
doofinder-for-woocommerce/includes/polyfills.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Instead of returning only the links to the categories assigned to the product, we also return the links to the parent categories. We've also removed the base category from the paths. 
Example:
- Before:
```
[
'product-category/sales/man-sales', 
'product-category/hoodies/special-hoodies'
]
```
- Now:
```
[
'sales', 
'sales/man-sales', 
'hoodies', 
'hoodies/special-hoodies'
]
```

Add parent category paths in the `category_merchandising` field.

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-klaviyo-integration.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/dooplugins/issues/1344
Related to:
- https://github.com/doofinder/apps-loader/pull/261

PLUGINRANGERS-1344 | Prevented custom integration logic to be loaded before Klaviyo's plugin JS

---

doofinder-for-woocommerce/doofinder-for-woocommerce.php
doofinder-for-woocommerce/includes/class-klaviyo-integration.php
doofinder-for-woocommerce/includes/class-setup-wizard.php
doofinder-for-woocommerce/readme.txt
package-lock.json
package.json

Required by:
- https://github.com/doofinder/support/issues/3922
This one might not solve the linked support issue, but it's a neceessary fix to apply anyway. In this PR there are actually two fixes:
- The one described in the issue, which is to add an option to prevent calling multiple time the Doofinder plugin setup Wizard
- Another one discussed with Renzo regarding Klaviyo JS. We should not load the Klaviyo custom var if the Klaviyo plugin is not active.
The original function was called long time ago, but the call was removed here: https://github.com/doofinder/doofinder-woocommerce/commit/f2579ed1b2316f491f701077cac05865005a7aa9#diff-adf83a38abba9ba2415ffe8d30b8ad7e450afdbc38ba4f634d4b7491b6acb8faL487

PLUGINRANGERS-3922 | Klaviyo + setup Wizard improvements
